# Generated by Django 3.1.1 on 2020-09-04 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='date',
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 23, 55, 42, 109781, tzinfo=utc)),
        ),
    ]
