# Generated by Django 3.1.1 on 2020-09-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200904_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='data_cadastro',
        ),
    ]
